# config.yaml
APP_NAME: Therapy Compliance Analyzer
ENVIRONMENT: production
DB_PATH: ./data/compliance.db
ENCRYPTION_KEY: "{{GENERATE_YOUR_OWN_KEY}}"  # Replace with generated key
OCR_ENGINE: Tesseract
NLP_MODELS:
  - ClinicalBERT
  - BioBERT
  - AraG
RUBRIC_PATH: ./data/rubrics/
REPORT_PATH: ./data/reports/
REPORT_RETENTION_HOURS: 24
AUTO_UPDATE: true 
ANALYTICS_PATH: ./data/analytics/
PHI_SCRUBBER: enabled
UI_MODE: responsive

# Section headers for parsing clinical notes
section_headers:
  - Subjective
  - Objective
  - Assessment
  - Plan

# OCR settings
ocr:
  preprocessing: true
  deskew: true
  resolution: 300

# Configuration for the RAG Pipeline
models:
  ner_model: "d4data/biomedical-ner-all"
  retriever: "pritamdeka/S-PubMedBert-MS-MARCO"
  llm_repo_id: "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
  llm_filename: "mistral-7b-instruct-v0.2.Q4_K_M.gguf"
  prompt_template: "src/core/prompt_template.txt"
  quantization: "none"
  nlg_prompt_template: "src/core/nlg_prompt_template.txt" # Path to the new prompt

retrieval_settings:
  similarity_top_k: 3

iterative_retrieval:
  max_iterations: 3

paths:
  index_dir: "sentence_index"
  docs_dir: "data"
