# Therapy Compliance Analyzer Configuration

# Database settings
database:
  url: "sqlite:///./compliance.db"
  echo: false

# Authentication settings
auth:
  secret_key: "your-super-secret-jwt-key-change-this-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# Maintenance settings
maintenance:
  purge_retention_days: 30
  purge_interval_days: 1

# Paths settings
paths:
  temp_upload_dir: "./temp"
  api_url: "http://localhost:8000"
  rule_dir: "./src/resources"
  medical_dictionary: "src/resources/medical_dictionary.txt"
  cache_dir: ".cache"
  logs_dir: "logs"

# LLM settings
llm:
  model_type: "ctransformers"
  context_length: 4096
  generation_params:
    temperature: 0.1
    max_new_tokens: 1024
    top_p: 0.9
    repeat_penalty: 1.1
    stop_sequences: ["</analysis>", "\n\n---"]

# Retrieval settings
retrieval:
  similarity_top_k: 10
  dense_model_name: "sentence-transformers/all-MiniLM-L6-v2"
  rrf_k: 60
  batch_size: 16
  max_sequence_length: 512

# Analysis settings
analysis:
  confidence_threshold: 0.75
  deterministic_focus: "- Treatment frequency documented\n- Goals reviewed or adjusted\n- Medical necessity justified"
  max_document_length: 50000
  chunk_overlap: 100

# Models settings
models:
  generator: "microsoft/DialoGPT-medium"
  retriever: "sentence-transformers/all-MiniLM-L6-v2"
  fact_checker: "microsoft/DialoGPT-medium"
  ner_ensemble: ["en_core_web_sm"]
  doc_classifier_prompt: "Classify this document type"
  analysis_prompt_template: "Analyze for compliance"
  nlg_prompt_template: "Generate recommendations"

# Habits framework
habits_framework:
  enabled: true
  visibility_level: "moderate"