# 99% ACCURACY Clinical Document Analyzer Configuration
# Clinical-grade precision with ensemble methods and advanced validation

# Application Settings
app_name: "Therapy Compliance Analyzer - 99% Accuracy"
version: "2.0.0"
debug: false

# AI Configuration
use_ai_mocks: false  # REAL AI with maximum accuracy

# Database Configuration
database:
  url: "sqlite:///./compliance.db"
  echo: false

# LLM Configuration - Meditron 7B Q5_K_M (Highest Quality)
llm:
  context_length: 4096
  gpu_layers: 0
  threads: 8
  hf_model_type: meditron
  model_type: ctransformers
  model_repo_id: TheBloke/meditron-7B-GGUF
  local_model_path: "models/meditron7b-high-accuracy/meditron-7b.Q5_K_M.gguf"
  generation_params:
    max_new_tokens: 1024
    repeat_penalty: 1.1
    stop_sequences:
    - </analysis>
    - "\n\n---"
    temperature: 0.05  # Very low for maximum accuracy
    top_p: 0.95

# Ensemble Configuration - Multiple Models for Voting
ensemble:
  enabled: true
  models:
    primary:
      name: "Meditron 7B Q5_K_M"
      weight: 0.4
      local_path: "models/meditron7b-high-accuracy"

    secondary:
      name: "ClinicalBERT"
      weight: 0.3
      local_path: "models/clinicalbert-ner"

    tertiary:
      name: "PubMedBERT"
      weight: 0.3
      local_path: "models/pubmedbert-factcheck"

  voting_strategy: "weighted_majority"
  confidence_threshold: 0.95
  require_consensus: true

# Advanced Fact-Checking Configuration
fact_checking:
  enabled: true
  models:
    primary_fact_checker: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
    secondary_fact_checker: "emilyalsentzer/Bio_ClinicalBERT"
    local_paths:
      pubmedbert: "models/pubmedbert-factcheck"
      clinicalbert: "models/clinicalbert-ner"

  verification_methods:
    medical_dictionary_validation: true
    clinical_guidelines_check: true
    compliance_rubric_verification: true
    cross_reference_sources: true
    expert_rule_validation: true

  confidence_threshold: 0.95
  require_multiple_sources: true

# Clinical Expert Rules Configuration
clinical_rules:
  enabled: true

  pt_compliance_rules:
    enabled: true
    file: "src/resources/pt_compliance_rubric.ttl"
    strict_mode: true

  ot_compliance_rules:
    enabled: true
    file: "src/resources/ot_compliance_rubric.ttl"
    strict_mode: true

  medical_necessity_rules:
    enabled: true
    validation_level: "strict"

  documentation_standards:
    enabled: true
    hipaa_compliance: true
    medical_necessity: true
    functional_goals: true

# Advanced NER Configuration - Multiple Models
ner_models:
  biomedical_primary:
    name: "ClinicalBERT Medical NER"
    model_id: "emilyalsentzer/Bio_ClinicalBERT"
    local_path: "models/clinicalbert-ner"
    priority: 1
    weight: 0.5

  biomedical_secondary:
    name: "Biomedical NER All"
    model_id: "d4data/biomedical-ner-all"
    local_path: "models/biomedical-ner"
    priority: 2
    weight: 0.3

  pathology_detection:
    name: "OpenMed Pathology Detection"
    model_id: "OpenMed/OpenMed-NER-PathologyDetect-PubMed-v2-109M"
    local_path: "models/openmed-ner"
    priority: 3
    weight: 0.2

  ensemble_ner: true
  confidence_threshold: 0.9

# High-Accuracy Embedding Models
embedding_models:
  bio_clinical:
    name: "BioClinicalBERT Embeddings"
    model_id: "emilyalsentzer/Bio_ClinicalBERT"
    local_path: "models/bio-clinical-embeddings"
    dimension: 768
    type: "clinical_specialized"

  sentence_transformer:
    name: "Sentence Transformers"
    model_id: "sentence-transformers/all-MiniLM-L6-v2"
    local_path: "models/sentence-transformers-minilm"
    dimension: 384
    type: "general"

  ensemble_embeddings: true

# Chat Configuration - High Accuracy
chat:
  enabled: true
  model: "dialogpt-medium"
  local_path: "models/dialogpt-medium"
  max_tokens: 256
  temperature: 0.1  # Low temperature for accuracy
  context_length: 512
  response_timeout: 10  # Longer timeout for accuracy
  fact_check_responses: true
  medical_accuracy_mode: true
  confidence_threshold: 0.9

# Analysis Settings - Maximum Accuracy
analysis:
  max_file_size_mb: 50
  supported_formats: ["pdf", "docx", "txt", "html"]
  phi_redaction: true
  confidence_threshold: 0.95  # Very high threshold
  fact_checking_enabled: true
  hallucination_detection: true
  medical_accuracy_mode: true
  ensemble_analysis: true
  cross_validation: true

  # Accuracy enhancement settings
  accuracy_enhancement:
    enable_ensemble_voting: true
    require_high_confidence: true
    validate_against_rules: true
    cross_check_findings: true
    expert_rule_validation: true

# API Settings
api:
  host: "127.0.0.1"
  port: 8001
  cors_origins: ["http://127.0.0.1:3001", "http://localhost:3001"]

# Logging
logging:
  level: "INFO"
  format: "json"
  file: "logs/app.log"

# Cache Settings - Optimized for Accuracy
cache:
  enabled: true
  ttl_seconds: 14400  # Longer cache for accuracy
  max_size_mb: 1000
  fact_check_cache: true
  ensemble_cache: true
  clinical_rules_cache: true

# 99% Accuracy Performance Settings
accuracy_mode:
  enabled: true
  target_accuracy: 0.99
  ensemble_enabled: true
  fact_checking_enabled: true
  clinical_rules_enabled: true
  cross_validation_enabled: true

  # Performance vs Accuracy balance
  accuracy_priority: "maximum"  # Prioritize accuracy over speed
  allow_slower_processing: true
  max_processing_time_minutes: 10

# Advanced Validation Settings
validation:
  enable_multi_model_validation: true
  enable_expert_rule_validation: true
  enable_cross_reference_validation: true
  enable_confidence_calibration: true
  enable_uncertainty_detection: true

  validation_thresholds:
    minimum_confidence: 0.95
    ensemble_agreement: 0.8
    fact_check_confidence: 0.9
    clinical_rule_compliance: 1.0

# Performance Monitoring - Accuracy Focus
performance:
  track_accuracy_metrics: true
  monitor_ensemble_agreement: true
  track_fact_checking_accuracy: true
  monitor_clinical_rule_compliance: true
  log_accuracy_improvements: true

  accuracy_targets:
    overall_accuracy: 0.99
    medical_entity_accuracy: 0.98
    compliance_accuracy: 0.99
    fact_checking_accuracy: 0.97

# Resource Optimization - Accuracy Priority
resources:
  max_memory_gb: 8  # Increased for ensemble
  cpu_threads: 12   # Increased for parallel processing
  enable_model_caching: true
  lazy_loading: false  # Load all models for accuracy
  ensemble_memory_limit_mb: 4096
  fact_checking_memory_limit_mb: 2048
