# --- Therapy Compliance Analyzer Configuration ---
# This file defines the settings for the application, organized into logical sections.
# Sensitive values like 'secret_key' should be set via environment variables in production.

api_url: "http://127.0.0.1:8000"
use_ai_mocks: true

database:
  url: "sqlite:///./compliance.db"
  echo: false

auth:
  # It is strongly recommended to override this with an environment variable:
  # export SECRET_KEY='your_super_secret_key_here'
  secret_key: "your_secret_key_here_for_dev"
  algorithm: "HS256"
  access_token_expire_minutes: 30

paths:
  # All paths are relative to the project root directory.
  temp_upload_dir: "tmp/uploads"
  rule_dir: "src/resources/rules"
  medical_dictionary: "src/resources/medical_dictionary.txt"
  analysis_prompt_template: "src/resources/prompts/analysis_prompt_template.txt"
  nlg_prompt_template: "src/resources/prompts/nlg_prompt_template.txt"
  doc_classifier_prompt: "src/resources/prompts/doc_classifier_prompt.txt"

llm:
  # Configuration for the primary Large Language Model used for analysis.
  # Using ClinicalCamel-5B as the default.
  repo: "TheBloke/ClinicalCamel-5B-GGUF"
  filename: "clinical-camel-5b.Q4_K_M.gguf"
  model_type: "llama"
  context_length: 2048
  generation_params:
    temperature: 0.1
    max_new_tokens: 2048

retrieval:
  # Settings for the document retrieval system.
  dense_model_name: "pritamdeka/S-PubMedBert-MS-MARCO"
  similarity_top_k: 3
  rrf_k: 60

analysis:
  # Parameters controlling the compliance analysis logic.
  confidence_threshold: 0.7


maintenance:
  # Settings for automated database maintenance tasks.
  purge_retention_days: 60
  purge_interval_days: 1