# config.yaml
APP_NAME: Therapy Compliance Analyzer
ENVIRONMENT: production
DB_PATH: ./data/compliance.db
ENCRYPTION_KEY: "" # Replace with your generated key

# OCR settings
ocr:
  preprocessing: true
  deskew: true
  resolution: 300

# Configuration for AI Models and Services
models:
  ner: "d4data/biomedical-ner-all"
  retriever: "pritamdeka/S-PubMedBert-MS-MARCO"
  generator: "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
  generator_filename: "mistral-7b-instruct-v0.2.Q4_K_M.gguf"
  
  # Prompt Templates
  analysis_prompt_template: "src/core/prompt_template.txt"
  nlg_prompt_template: "src/core/nlg_prompt_template.txt"
  doc_classifier_prompt: "src/core/doc_classifier_prompt.txt"

llm_settings:
  gpu_layers: 0
  model_type: "mistral"
  context_length: 4096
  generation_params:
    max_new_tokens: 2048
    temperature: 0.2
    top_p: 0.95
    repetition_penalty: 1.1

# Retrieval settings
retrieval_settings:
  similarity_top_k: 3
