# --- Therapy Compliance Analyzer Configuration ---
# This file defines the settings for the application, organized into logical sections.
# Sensitive values like 'secret_key' should be set via environment variables in production.

use_ai_mocks: true
enable_director_dashboard: true

database:
  url: "sqlite:///./compliance.db"
  echo: false

auth:
  secret_key: "your_secret_key_here"  # Should be overridden by environment variable in production
  algorithm: "HS256"
  access_token_expire_minutes: 30

maintenance:
  purge_retention_days: 60
  purge_interval_days: 1

paths:
  temp_upload_dir: "/tmp/uploads"
  api_url: "http://127.0.0.1:8000"
  rule_dir: "src/resources/rules"

models:
  generator_profiles:
    standard:
      repo: "microsoft/Phi-3-mini-4k-instruct-gguf"
      filename: "Phi-3-mini-4k-instruct.Q4_K_M.gguf"
      max_system_gb: 11.0
    enhanced:
      repo: "meta-llama/Meta-Llama-3-8B-Instruct-GGUF"
      filename: "Meta-Llama-3-8B-Instruct.Q4_K_M.gguf"
      min_system_gb: 11.0
  chat:
    repo: "TheBloke/ClinicalCamel-5B-GGUF"
    filename: "clinical-camel-5b.Q4_K_M.gguf"
    model_type: "llama"
    context_length: 2048
  retriever: "sentence-transformers/all-MiniLM-L6-v2"
  fact_checker: "google/flan-t5-base"
  ner_ensemble:
    - "OpenMed/OpenMed-NER-PathologyDetect-PubMed-v2-109M"
    - "d4data/biomedical-ner-all"
  phi_scrubber:
    general: "beki/en_spacy_pii_fast"
    biomedical: "bigcode/starpii"
  doc_classifier_prompt: "src/resources/prompts/doc_classifier_prompt.txt"
  analysis_prompt_template: "src/resources/prompts/analysis_prompt_template.txt"
  nlg_prompt_template: "src/resources/prompts/nlg_prompt_template.txt"

llm:
  model_type: "llama"
  context_length: 2048
  generation_params:
    temperature: 0.1
    max_new_tokens: 2048

retrieval:
  dense_model_name: "pritamdeka/S-PubMedBert-MS-MARCO"
  similarity_top_k: 3
  rrf_k: 60

analysis:
  confidence_threshold: 0.7
  deterministic_focus: |
    - Treatment frequency documented
    - Goals reviewed or adjusted
    - Medical necessity justified
