# Therapy Compliance Analyzer Configuration

use_ai_mocks: false  # Use real models but lightweight ones
enable_director_dashboard: true

database:
  url: "sqlite:///./compliance.db"
  echo: false

# Authentication settings
auth:
  secret_key: "your-super-secret-jwt-key-change-this-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# Maintenance settings
maintenance:
  purge_retention_days: 30
  purge_interval_days: 1

# Paths settings
paths:
  temp_upload_dir: "./temp"
  api_url: "http://localhost:8001"
  rule_dir: "./src/resources"
  medical_dictionary: "src/resources/medical_dictionary.txt"
  cache_dir: ".cache"
  logs_dir: "logs"

models:
  # Use only BERT-based models to avoid T5/sentencepiece conflicts
  generator_profiles:
    standard:
      repo: "distilbert-base-uncased"  # Lightweight BERT model
      filename: ""
      revision: "main"
      max_system_gb: 8.0
    enhanced:
      repo: "bert-base-uncased"  # Standard BERT model
      filename: ""
      revision: "main"
      min_system_gb: 8.0
  chat:
    repo: "distilbert-base-uncased"
    filename: ""
    revision: "main"
    model_type: "bert"
    context_length: 512
  retriever: "sentence-transformers/all-MiniLM-L6-v2"
  fact_checker: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"  # Medical BERT
  ner_ensemble:
    - "d4data/biomedical-ner-all"
  phi_scrubber:
    general: "beki/en_spacy_pii_fast"
    biomedical: "bigcode/starpii"
  doc_classifier_prompt: "src/resources/prompts/doc_classifier_prompt.txt"
  analysis_prompt_template: "src/resources/prompts/analysis_prompt_template.txt"
  nlg_prompt_template: "src/resources/prompts/nlg_prompt_template.txt"

# LLM settings
llm:
  model_type: "ctransformers"
  context_length: 4096
  generation_params:
    temperature: 0.1
    max_new_tokens: 1024
    top_p: 0.9
    repeat_penalty: 1.1
    stop_sequences: ["</analysis>", "\n\n---"]

# Retrieval settings
retrieval:
  similarity_top_k: 10
  dense_model_name: "sentence-transformers/all-MiniLM-L6-v2"
  rrf_k: 60
  batch_size: 16
  max_sequence_length: 512

# Analysis settings
analysis:
  confidence_threshold: 0.75
  deterministic_focus: "- Treatment frequency documented\n- Goals reviewed or adjusted\n- Medical necessity justified"
  max_document_length: 50000
  chunk_overlap: 100

# Models settings
models:
  generator: "microsoft/DialoGPT-medium"
  retriever: "sentence-transformers/all-MiniLM-L6-v2"
  fact_checker: "microsoft/DialoGPT-medium"
  ner_ensemble: ["d4data/biomedical-ner-all"]
  doc_classifier_prompt: "src/resources/prompts/doc_classifier_prompt.txt"
  analysis_prompt_template: "src/resources/prompts/analysis_prompt_template.txt"
  nlg_prompt_template: "src/resources/prompts/nlg_prompt_template.txt"

# Habits framework
habits_framework:
  enabled: true
  visibility_level: "moderate"