ANALYTICS_PATH: ./data/analytics/
APP_NAME: Therapy Compliance Analyzer
AUTO_UPDATE: true
DB_PATH: ./data/compliance.db
ENCRYPTION_KEY: '{{GENERATE_YOUR_OWN_KEY}}'
ENVIRONMENT: production
NLP_MODELS:
- ClinicalBERT
- BioBERT
- AraG
OCR_ENGINE: Tesseract
PHI_SCRUBBER: enabled
REPORT_PATH: ./data/reports/
REPORT_RETENTION_HOURS: 24
RUBRIC_PATH: ./data/rubrics/
UI_MODE: responsive
iterative_retrieval:
  max_iterations: 3
models:
  generator: nabilfaieaz/tinyllama-med-full
  ner_model: OpenMed/OpenMed-NER-PathologyDetect-PubMed-v2-109M
  prompt_template: default_prompt.txt
  quantization: none
  retriever: pritamdeka/S-PubMedBert-MS-MARCO
  summarizer: sshleifer/distilbart-cnn-12-6
ocr:
  deskew: true
  preprocessing: true
  resolution: 300
paths:
  docs_dir: data
  index_dir: sentence_index
performance_profile: low
quantization: 8bit
retrieval_settings:
  similarity_top_k: 3
reviewer_difficulty: strict
section_headers:
- Subjective
- Objective
- Assessment
- Plan
