database:
  url: "sqlite:///./compliance.db"

auth:
  secret_key: "a_very_secret_key"
  algorithm: "HS256"
  access_token_expire_minutes: 30

maintenance:
  purge_retention_days: 30

models:
  generator: "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
  generator_filename: "mistral-7b-instruct-v0.2.Q4_K_M.gguf"
  retriever: "pritamdeka/S-PubMedBert-MS-MARCO"
  fact_checker: "hamish-haggerty/t5-base-e2e-qg"
  doc_classifier_prompt: "src/resources/prompts/doc_classifier_prompt.txt"
  analysis_prompt_template: "src/resources/prompts/analysis_prompt_template.txt"
  ner_primary_model: "d4data/biomedical-ner-all"
  ner_ensemble:
    - "d4data/biomedical-ner-all"
  nlg_prompt_template: "src/resources/prompts/nlg_prompt_template.txt"

llm_settings:
  model_type: "mistral"
  context_length: 4096
  generation_params:
    temperature: 0.1
    max_new_tokens: 8192

retrieval_settings:
  similarity_top_k: 5