analysis:
  chunk_overlap: 100
  confidence_threshold: 0.75
  deterministic_focus: '- Treatment frequency documented\n- Goals reviewed or adjusted\n-
    Medical necessity justified'
  max_document_length: 50000
auth:
  access_token_expire_minutes: 30
  algorithm: HS256
database:
  echo: false
  url: sqlite:///./compliance.db
enable_director_dashboard: true
habits_framework:
  enabled: true
  visibility_level: moderate
llm:
  context_length: 4096
  generation_params:
    max_new_tokens: 1024
    repeat_penalty: 1.1
    stop_sequences:
    - </analysis>
    - \n\n---
    temperature: 0.1
    top_p: 0.9
  model_type: ctransformers
maintenance:
  purge_interval_days: 1
  purge_retention_days: 30
models:
  analysis_prompt_template: src/resources/prompts/analysis_prompt_template.txt
  doc_classifier_prompt: src/resources/prompts/doc_classifier_prompt.txt
  fact_checker: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
  generator: TheBloke/meditron-7B-GGUF
  generator_filename: meditron-7b.Q4_K_M.gguf
  generator_local_path: models/meditron
  generator_profiles:
    clinical_fast:
      fast_mode: true
      filename: meditron-7b.Q4_K_M.gguf
      max_system_gb: 8.0
      max_tokens: 512
      repo: TheBloke/meditron-7B-GGUF
      revision: main
      temperature: 0.1
    clinical_q4_balanced:
      filename: meditron-7b.Q4_K_M.gguf
      max_system_gb: 16.0
      repo: TheBloke/meditron-7B-GGUF
      revision: main
    clinical_q5_quality:
      filename: meditron-7b.Q5_K_M.gguf
      max_system_gb: 24.0
      min_system_gb: 16.0
      repo: TheBloke/meditron-7B-GGUF
      revision: main
    clinical_q6_precision:
      filename: meditron-7b.Q6_K.gguf
      min_system_gb: 24.0
      repo: TheBloke/meditron-7B-GGUF
      revision: main
  ner_ensemble:
  - d4data/biomedical-ner-all
  - OpenMed/OpenMed-NER-PathologyDetect-PubMed-v2-109M
  nlg_prompt_template: src/resources/prompts/nlg_prompt_template.txt
  reranker: cross-encoder/ms-marco-MiniLM-L-6-v2
  retriever: pritamdeka/S-PubMedBert-MS-MARCO
paths:
  api_url: http://localhost:8001
  cache_dir: .cache
  logs_dir: logs
  medical_dictionary: src/resources/medical_dictionary.txt
  rule_dir: ./src/resources
  temp_upload_dir: ./temp
performance:
  enable_caching: true
  fast_mode: true
  max_chunk_size: 1000
  parallel_processing: false
  reduce_context_window: true
  simple_report_mode: true
  skip_advanced_ner: true
  skip_fact_checking: true
retrieval:
  batch_size: 16
  dense_model_name: pritamdeka/S-PubMedBert-MS-MARCO
  max_sequence_length: 512
  rrf_k: 60
  similarity_top_k: 10
use_ai_mocks: false
