# Lightweight Configuration for Therapy Compliance Analyzer
# Optimized for reliable startup and core functionality

use_ai_mocks: true  # Use mocks to avoid LLM loading issues
enable_director_dashboard: true

database:
  url: "sqlite:///./compliance.db"
  echo: false
  pool_size: 5  # Reduced for lighter load
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600
  sqlite_optimizations: true
  connection_timeout: 20

auth:
  secret_key: "your_secret_key_here"
  algorithm: "HS256"
  access_token_expire_minutes: 30

maintenance:
  purge_retention_days: 60
  purge_interval_days: 1

paths:
  temp_upload_dir: "/tmp/uploads"
  api_url: "http://127.0.0.1:8000"
  rule_dir: "src/resources/rules"
  medical_dictionary: "src/resources/medical_dictionary.txt"

models:
  # Use GGUF format models compatible with ctransformers
  generator_profiles:
    standard:
      repo: "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"  # Tiny, fast GGUF model
      filename: "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
      revision: "main"
      max_system_gb: 2.0  # Very light
    enhanced:
      repo: "TheBloke/Phi-2-GGUF"  # Small but capable GGUF model
      filename: "phi-2.Q4_K_M.gguf"
      revision: "main"
      min_system_gb: 4.0
  chat:
    repo: "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"
    filename: "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
    revision: "main"
    model_type: "llama"
    context_length: 1024
  retriever: "sentence-transformers/all-MiniLM-L6-v2"  # Keep this - it's good
  fact_checker: "google/flan-t5-small"  # Use small version
  ner_ensemble:
    - "d4data/biomedical-ner-all"  # Keep just one to start faster
  phi_scrubber:
    general: "beki/en_spacy_pii_fast"
    biomedical: "bigcode/starpii"
  doc_classifier_prompt: "src/resources/prompts/doc_classifier_prompt.txt"
  analysis_prompt_template: "src/resources/prompts/analysis_prompt_template.txt"
  nlg_prompt_template: "src/resources/prompts/nlg_prompt_template.txt"

llm:
  model_type: "llama"  # Use llama for GGUF models
  context_length: 1024  # Smaller context
  generation_params:
    temperature: 0.1
    max_new_tokens: 512  # Much smaller

retrieval:
  dense_model_name: "sentence-transformers/all-MiniLM-L6-v2"  # Use same as retriever
  similarity_top_k: 3
  rrf_k: 60

analysis:
  confidence_threshold: 0.7
  deterministic_focus: |
    - Treatment frequency documented
    - Goals reviewed or adjusted
    - Medical necessity justified

# Simplified habits framework
habits_framework:
  enabled: true
  visibility_level: "moderate"
  report_integration:
    show_habit_tags: true
    show_personal_development_section: true
    show_habit_tooltips: true
    habit_section_expanded_by_default: false
  dashboard_integration:
    show_growth_journey_tab: true
    show_weekly_focus_widget: true
    show_habit_progression_charts: true
    show_peer_comparison: false
  ai_features:
    use_ai_mapping: false  # Disable to avoid LLM dependency
    use_ai_coaching: false
    personalized_strategies: true
  gamification:
    enabled: true
    show_badges: true
    show_streaks: true
    show_milestones: true
    notifications_enabled: false
  education:
    show_habit_resources: true
    show_clinical_examples: true
    show_improvement_strategies: true
    show_templates: true
  privacy:
    track_progression: true
    anonymous_analytics: true
    share_achievements: false
  advanced:
    habit_confidence_threshold: 0.6
    focus_area_threshold: 0.20
    mastery_threshold: 0.05
    weekly_focus_enabled: true
    auto_suggest_templates: true