# Lightweight 99% Accuracy Configuration
# Using existing models with advanced accuracy techniques

# Application Settings
app_name: "Therapy Compliance Analyzer - Lightweight 99% Accuracy"
version: "2.0.0"
debug: false

# AI Configuration
use_ai_mocks: false  # REAL AI with maximum accuracy

# Database Configuration
database:
  url: "sqlite:///./compliance.db"
  echo: false

# LLM Configuration - Meditron 7B Q4_K_M (Existing - Optimized)
llm:
  context_length: 4096
  gpu_layers: 0
  threads: 8
  hf_model_type: meditron
  model_type: ctransformers
  model_repo_id: TheBloke/meditron-7B-GGUF
  local_model_path: "models/meditron7b/meditron-7b.Q4_K_M.gguf"
  generation_params:
    max_new_tokens: 1024
    repeat_penalty: 1.1
    stop_sequences:
    - </analysis>
    - "\n\n---"
    temperature: 0.05  # Very low for maximum accuracy
    top_p: 0.95

# Lightweight Ensemble - Using Existing Models
lightweight_ensemble:
  enabled: true
  models:
    primary:
      name: "Meditron 7B Q4_K_M"
      weight: 0.6
      local_path: "models/meditron7b"

    secondary:
      name: "DialoGPT Medium"
      weight: 0.4
      local_path: "models/dialogpt-medium"

  voting_strategy: "weighted_consensus"
  confidence_threshold: 0.9
  require_agreement: true

# Advanced Fact-Checking with Existing Models
fact_checking:
  enabled: true
  models:
    primary_fact_checker: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
    local_path: "models/biomedical-ner"  # Use existing biomedical NER

  verification_methods:
    medical_dictionary_validation: true
    clinical_guidelines_check: true
    compliance_rubric_verification: true
    cross_reference_sources: true
    expert_rule_validation: true

  confidence_threshold: 0.9
  require_multiple_sources: true

# Clinical Expert Rules Configuration - ALL RUBRICS
clinical_rules:
  enabled: true

  pt_compliance_rules:
    enabled: true
    file: "src/resources/pt_compliance_rubric.ttl"
    strict_mode: true

  ot_compliance_rules:
    enabled: true
    file: "src/resources/ot_compliance_rubric.ttl"
    strict_mode: true

  slp_compliance_rules:
    enabled: true
    file: "src/resources/slp_compliance_rubric.ttl"
    strict_mode: true

  medical_necessity_rules:
    enabled: true
    validation_level: "strict"

  documentation_standards:
    enabled: true
    hipaa_compliance: true
    medical_necessity: true
    functional_goals: true

# Advanced NER Configuration - Existing Models
ner_models:
  biomedical_primary:
    name: "Biomedical NER All"
    model_id: "d4data/biomedical-ner-all"
    local_path: "models/biomedical-ner"
    priority: 1
    weight: 0.7

  pathology_detection:
    name: "OpenMed Pathology Detection"
    model_id: "OpenMed/OpenMed-NER-PathologyDetect-PubMed-v2-109M"
    local_path: "models/openmed-ner"
    priority: 2
    weight: 0.3

  ensemble_ner: true
  confidence_threshold: 0.9

# High-Accuracy Embedding Models - Existing
embedding_models:
  sentence_transformer:
    name: "Sentence Transformers MiniLM"
    model_id: "sentence-transformers/all-MiniLM-L6-v2"
    local_path: "models/sentence-transformers-minilm"
    dimension: 384
    type: "general"

# Chat Configuration - High Accuracy
chat:
  enabled: true
  model: "dialogpt-medium"
  local_path: "models/dialogpt-medium"
  max_tokens: 256
  temperature: 0.1  # Low temperature for accuracy
  context_length: 512
  response_timeout: 10
  fact_check_responses: true
  medical_accuracy_mode: true
  confidence_threshold: 0.9

# Analysis Settings - Maximum Accuracy with Existing Models
analysis:
  max_file_size_mb: 50
  supported_formats: ["pdf", "docx", "txt", "html"]
  phi_redaction: true
  confidence_threshold: 0.95  # Very high threshold
  fact_checking_enabled: true
  hallucination_detection: true
  medical_accuracy_mode: true
  lightweight_ensemble: true
  cross_validation: true

  # Accuracy enhancement settings
  accuracy_enhancement:
    enable_lightweight_ensemble: true
    require_high_confidence: true
    validate_against_rules: true
    cross_check_findings: true
    expert_rule_validation: true
    multiple_validation_passes: true

# API Settings
api:
  host: "127.0.0.1"
  port: 8001
  cors_origins: ["http://127.0.0.1:3001", "http://localhost:3001"]

# Logging
logging:
  level: "INFO"
  format: "json"
  file: "logs/app.log"

# Cache Settings - Optimized for Accuracy
cache:
  enabled: true
  ttl_seconds: 14400  # Longer cache for accuracy
  max_size_mb: 1000
  fact_check_cache: true
  ensemble_cache: true
  clinical_rules_cache: true

# Lightweight 99% Accuracy Performance Settings
accuracy_mode:
  enabled: true
  target_accuracy: 0.99
  lightweight_ensemble_enabled: true
  fact_checking_enabled: true
  clinical_rules_enabled: true
  cross_validation_enabled: true

  # Performance vs Accuracy balance
  accuracy_priority: "maximum"
  allow_slower_processing: true
  max_processing_time_minutes: 10
  use_existing_models_only: true

# Advanced Validation Settings
validation:
  enable_multi_model_validation: true
  enable_expert_rule_validation: true
  enable_cross_reference_validation: true
  enable_confidence_calibration: true
  enable_uncertainty_detection: true

  validation_thresholds:
    minimum_confidence: 0.95
    ensemble_agreement: 0.8
    fact_check_confidence: 0.9
    clinical_rule_compliance: 1.0

  # Multiple validation passes
  validation_passes:
    pass_1: "primary_analysis"
    pass_2: "ensemble_validation"
    pass_3: "fact_checking"
    pass_4: "clinical_rules"
    pass_5: "final_validation"

# Performance Monitoring - Accuracy Focus
performance:
  track_accuracy_metrics: true
  monitor_ensemble_agreement: true
  track_fact_checking_accuracy: true
  monitor_clinical_rule_compliance: true
  log_accuracy_improvements: true

  accuracy_targets:
    overall_accuracy: 0.99
    medical_entity_accuracy: 0.98
    compliance_accuracy: 0.99
    fact_checking_accuracy: 0.97

# Resource Optimization - Lightweight but Accurate
resources:
  max_memory_gb: 6  # Moderate increase for accuracy
  cpu_threads: 8    # Existing CPU usage
  enable_model_caching: true
  lazy_loading: true  # Keep lightweight
  ensemble_memory_limit_mb: 2048
  fact_checking_memory_limit_mb: 1024
