# Ultra-Lightweight 99% Accuracy Configuration
# Creative optimization with model repurposing and smart thresholds

# Application Settings
app_name: "Therapy Compliance Analyzer - Ultra-Lightweight 99% Accuracy"
version: "2.0.0"
debug: false

# AI Configuration
use_ai_mocks: false  # REAL AI with maximum efficiency

# Database Configuration
database:
  url: "sqlite:///./compliance.db"
  echo: false

# LLM Configuration - Meditron 7B Q4_K_M (Primary)
llm:
  context_length: 4096
  gpu_layers: 0
  threads: 8
  hf_model_type: meditron
  model_type: ctransformers
  model_repo_id: TheBloke/meditron-7B-GGUF
  local_model_path: "models/meditron7b/meditron-7b.Q4_K_M.gguf"
  generation_params:
    max_new_tokens: 1024
    repeat_penalty: 1.1
    stop_sequences:
    - </analysis>
    - "\n\n---"
    temperature: 0.05  # Very low for maximum accuracy
    top_p: 0.95

# CREATIVE OPTIMIZATION: Smart Model Repurposing
smart_model_usage:
  enabled: true

  # Meditron 7B - Multi-Purpose (Primary Analysis + Fact-Checking)
  meditron_7b:
    primary_use: "medical_analysis"
    secondary_use: "fact_checking"  # Repurpose for fact-checking
    tertiary_use: "confidence_scoring"
    weight: 0.7

  # DialoGPT Medium - Multi-Purpose (Chat + Text Generation + Validation)
  dialogpt_medium:
    primary_use: "chat_assistant"
    secondary_use: "text_generation"
    tertiary_use: "validation_checking"  # Repurpose for validation
    weight: 0.3

  # Biomedical NER - Multi-Purpose (NER + Fact-Checking + Validation)
  biomedical_ner:
    primary_use: "entity_extraction"
    secondary_use: "fact_verification"  # Repurpose for fact-checking
    tertiary_use: "medical_validation"
    weight: 0.5

  # OpenMed NER - Specialized (Pathology Only)
  openmed_ner:
    primary_use: "pathology_detection"
    specialized_only: true  # Keep specialized, drop general use
    weight: 0.2

  # Sentence Transformers - Multi-Purpose (Embeddings + Similarity + Validation)
  sentence_transformers:
    primary_use: "document_embeddings"
    secondary_use: "similarity_matching"
    tertiary_use: "consistency_checking"  # Repurpose for validation
    weight: 0.3

# Lightweight Ensemble - Smart Voting
lightweight_ensemble:
  enabled: true
  models:
    primary:
      name: "Meditron 7B Multi-Purpose"
      weight: 0.6
      functions: ["analysis", "fact_checking", "confidence"]

    secondary:
      name: "DialoGPT Medium Multi-Purpose"
      weight: 0.4
      functions: ["chat", "validation", "text_gen"]

  voting_strategy: "smart_weighted_consensus"
  confidence_threshold: 0.92  # Optimized threshold
  require_agreement: true

# Advanced Fact-Checking - Repurposed Models
fact_checking:
  enabled: true
  models:
    primary_fact_checker: "meditron-7b"  # Repurpose Meditron
    secondary_fact_checker: "biomedical-ner"  # Repurpose Biomedical NER
    tertiary_fact_checker: "sentence-transformers"  # Repurpose for consistency

  verification_methods:
    medical_dictionary_validation: true
    clinical_guidelines_check: true
    compliance_rubric_verification: true
    cross_reference_sources: true
    expert_rule_validation: true
    consistency_checking: true  # New method using sentence transformers

  confidence_threshold: 0.92  # Optimized threshold
  require_multiple_sources: true

# Clinical Expert Rules Configuration - Organized Rubrics
clinical_rules:
  enabled: true

  # Organized rubric paths
  rubric_directory: "src/resources/rubrics"

  pt_compliance_rules:
    enabled: true
    file: "src/resources/rubrics/pt_compliance_rubric.ttl"
    strict_mode: true

  ot_compliance_rules:
    enabled: true
    file: "src/resources/rubrics/ot_compliance_rubric.ttl"
    strict_mode: true

  slp_compliance_rules:
    enabled: true
    file: "src/resources/rubrics/slp_compliance_rubric.ttl"
    strict_mode: true

  medical_necessity_rules:
    enabled: true
    validation_level: "strict"

  documentation_standards:
    enabled: true
    hipaa_compliance: true
    medical_necessity: true
    functional_goals: true

# Optimized NER Configuration - Repurposed Models
ner_models:
  biomedical_multi_purpose:
    name: "Biomedical NER Multi-Purpose"
    model_id: "d4data/biomedical-ner-all"
    local_path: "models/biomedical-ner"
    priority: 1
    weight: 0.7
    functions: ["entity_extraction", "fact_verification", "medical_validation"]

  pathology_specialized:
    name: "OpenMed Pathology Detection"
    model_id: "OpenMed/OpenMed-NER-PathologyDetect-PubMed-v2-109M"
    local_path: "models/openmed-ner"
    priority: 2
    weight: 0.3
    functions: ["pathology_detection"]  # Specialized only

  ensemble_ner: true
  confidence_threshold: 0.92  # Optimized threshold

# High-Accuracy Embedding Models - Multi-Purpose
embedding_models:
  sentence_transformer_multi:
    name: "Sentence Transformers Multi-Purpose"
    model_id: "sentence-transformers/all-MiniLM-L6-v2"
    local_path: "models/sentence-transformers-minilm"
    dimension: 384
    type: "multi_purpose"
    functions: ["embeddings", "similarity", "consistency_checking"]

# Chat Configuration - High Accuracy
chat:
  enabled: true
  model: "dialogpt-medium"
  local_path: "models/dialogpt-medium"
  max_tokens: 256
  temperature: 0.1
  context_length: 512
  response_timeout: 10
  fact_check_responses: true
  medical_accuracy_mode: true
  confidence_threshold: 0.92  # Optimized threshold

# Analysis Settings - Maximum Efficiency
analysis:
  max_file_size_mb: 50
  supported_formats: ["pdf", "docx", "txt", "html"]
  phi_redaction: true
  confidence_threshold: 0.92  # Optimized threshold
  fact_checking_enabled: true
  hallucination_detection: true
  medical_accuracy_mode: true
  smart_ensemble: true
  cross_validation: true

  # Efficiency settings
  accuracy_enhancement:
    enable_smart_ensemble: true
    require_high_confidence: true
    validate_against_rules: true
    cross_check_findings: true
    expert_rule_validation: true
    multi_purpose_validation: true

# API Settings
api:
  host: "127.0.0.1"
  port: 8001
  cors_origins: ["http://127.0.0.1:3001", "http://localhost:3001"]

# Logging
logging:
  level: "INFO"
  format: "json"
  file: "logs/app.log"

# Cache Settings - Optimized for Efficiency
cache:
  enabled: true
  ttl_seconds: 14400
  max_size_mb: 800
  fact_check_cache: true
  ensemble_cache: true
  clinical_rules_cache: true
  multi_purpose_cache: true

# Ultra-Lightweight 99% Accuracy Performance Settings
accuracy_mode:
  enabled: true
  target_accuracy: 0.99
  smart_ensemble_enabled: true
  fact_checking_enabled: true
  clinical_rules_enabled: true
  cross_validation_enabled: true
  multi_purpose_models: true

  # Performance vs Accuracy balance
  accuracy_priority: "maximum"
  allow_slower_processing: true
  max_processing_time_minutes: 10
  use_existing_models_only: true
  smart_model_repurposing: true

# Advanced Validation Settings
validation:
  enable_multi_purpose_validation: true
  enable_expert_rule_validation: true
  enable_cross_reference_validation: true
  enable_confidence_calibration: true
  enable_uncertainty_detection: true
  enable_consistency_checking: true

  validation_thresholds:
    minimum_confidence: 0.92  # Optimized threshold
    ensemble_agreement: 0.8
    fact_check_confidence: 0.92  # Optimized threshold
    clinical_rule_compliance: 1.0
    consistency_threshold: 0.9

  # Smart validation passes
  validation_passes:
    pass_1: "primary_analysis"
    pass_2: "smart_ensemble_validation"
    pass_3: "multi_purpose_fact_checking"
    pass_4: "clinical_rules_validation"
    pass_5: "consistency_checking"
    pass_6: "final_validation"

# Performance Monitoring - Efficiency Focus
performance:
  track_accuracy_metrics: true
  monitor_smart_ensemble_agreement: true
  track_multi_purpose_fact_checking: true
  monitor_clinical_rule_compliance: true
  log_efficiency_improvements: true
  track_model_repurposing_efficiency: true

  accuracy_targets:
    overall_accuracy: 0.99
    medical_entity_accuracy: 0.98
    compliance_accuracy: 0.99
    fact_checking_accuracy: 0.97
    efficiency_score: 0.95

# Resource Optimization - Ultra-Lightweight
resources:
  max_memory_gb: 5  # Optimized for efficiency
  cpu_threads: 8
  enable_model_caching: true
  lazy_loading: true
  smart_model_switching: true
  multi_purpose_memory_limit_mb: 2048
  fact_checking_memory_limit_mb: 1024
  ensemble_memory_limit_mb: 1536
