# config.yaml
APP_NAME: Therapy Compliance Analyzer
ENVIRONMENT: production
DB_PATH: ./data/compliance.db
# IMPORTANT: Generate a secure, random key for encryption.
# You can use a command like `openssl rand -hex 32` to generate a key.
# Store this key securely and do not commit it to version control.
ENCRYPTION_KEY: "" # Replace with your generated key
OCR_ENGINE: Tesseract
NLP_MODELS:
  - ClinicalBERT
  - BioBERT
  - AraG
RUBRIC_PATH: ./data/rubrics/
REPORT_PATH: ./data/reports/
REPORT_RETENTION_HOURS: 24
AUTO_UPDATE: true 
ANALYTICS_PATH: ./data/analytics/
PHI_SCRUBBER: enabled
UI_MODE: responsive

# Section headers for parsing clinical notes
section_headers:
  - Subjective
  - Objective
  - Assessment
  - Plan

# OCR settings
ocr:
  preprocessing: true
  deskew: true
  resolution: 300

# Configuration for the RAG Pipeline
models:
  ner_model: "OpenMed/OpenMed-NER-PathologyDetect-PubMed-v2-109M"
  retriever: "pritamdeka/S-PubMedBert-MS-MARCO"
  generator: "nabilfaieaz/tinyllama-med-full"
  summarizer: "sshleifer/distilbart-cnn-12-6"
  prompt_template: "default_prompt.txt"
  quantization: "none"

retrieval_settings:
  similarity_top_k: 3

iterative_retrieval:
  max_iterations: 3

paths:
  index_dir: "sentence_index"
  docs_dir: "data"
