# config.yaml
APP_NAME: Therapy Compliance Analyzer
ENVIRONMENT: production
DB_PATH: ./data/compliance.db
ENCRYPTION_KEY: "" # Replace with your generated key

# OCR settings
ocr:
  preprocessing: true
  deskew: true
  resolution: 300

# Configuration for AI Models and Services
models:
  # State-of-the-art NER for medical pathology detection
  ner: "OpenMed/OpenMed-NER-PathologyDetect-PubMed-v2-109M"
  
  # Best-in-class sentence transformer for medical semantic search
  retriever: "pritamdeka/S-PubMedBert-MS-MARCO"
  
  # Fast, locally-deployable medical text generator
  generator: "nabilfaieaz/tinyllama-med-full"
  
  # Prompt Templates
  analysis_prompt_template: "src/core/prompt_template.txt"
  nlg_prompt_template: "src/core/nlg_prompt_template.txt"
  doc_classifier_prompt: "src/core/doc_classifier_prompt.txt"

# Settings for the generator model
llm_settings:
  # Note: These settings may need to be adjusted for TinyLLaMA
  gpu_layers: 0
  model_type: "llama" # Changed from mistral to llama for TinyLLaMA
  context_length: 2048 # Adjusted for TinyLLaMA
  generation_params:
    max_new_tokens: 1024
    temperature: 0.3
    top_p: 0.95
    repetition_penalty: 1.1

# Retrieval settings
retrieval_settings:
  similarity_top_k: 3

# Database Maintenance
purge_retention_days: 60
