version: '3.8'

services:
  # Redis service for Celery message brokering
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The FastAPI application service
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    # The command is inherited from the Dockerfile's CMD instruction

  # The Celery worker service
  worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    # Override the default command to start the Celery worker
    command: ["celery", "-A", "src.celery_app", "worker", "--loglevel=info"]

volumes:
  redis_data:
