# --- Therapy Compliance Analyzer Configuration ---
# This file defines the settings for the application, organized into logical sections.
# Sensitive values like 'secret_key' should be set via environment variables in production.

use_ai_mocks: true
enable_director_dashboard: true

database:
  url: "sqlite:///./compliance.db"
  echo: false
  # Performance and reliability settings
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  # SQLite-specific optimizations
  sqlite_optimizations: true
  connection_timeout: 20

auth:
  secret_key: "your_secret_key_here"  # Should be overridden by environment variable in production
  algorithm: "HS256"
  access_token_expire_minutes: 30

maintenance:
  purge_retention_days: 60
  purge_interval_days: 1

paths:
  temp_upload_dir: "/tmp/uploads"
  api_url: "http://127.0.0.1:9000"
  rule_dir: "src/resources/rules"

models:
  generator_profiles:
    standard:
      repo: "QuantFactory/Phi-3-mini-4k-instruct-GGUF"
      filename: "Phi-3-mini-4k-instruct.Q4_K_M.gguf"
      revision: "7dcfbd4b7f6f2718048dc171d977aab914075776"
      max_system_gb: 11.0
    enhanced:
      repo: "second-state/Llama-3-8B-Instruct-GGUF"
      filename: "Meta-Llama-3-8B-Instruct-Q4_K_M.gguf"
      revision: "05372b81638de3fcbfe8945745dd7666b7bc47e3"
      min_system_gb: 11.0
  chat:
    repo: "TheBloke/medicine-chat-GGUF"
    filename: "medicine-chat.Q4_K_M.gguf"
    revision: "4b698781e153498a28f456df766e8cd3c2f22212"
    model_type: "llama"
    context_length: 2048
  retriever: "sentence-transformers/all-MiniLM-L6-v2"
  fact_checker: "google/flan-t5-base"
  ner_ensemble:
    - "OpenMed/OpenMed-NER-PathologyDetect-PubMed-v2-109M"
    - "d4data/biomedical-ner-all"
  phi_scrubber:
    general: "beki/en_spacy_pii_fast"
    biomedical: "bigcode/starpii"
  doc_classifier_prompt: "src/resources/prompts/doc_classifier_prompt.txt"
  analysis_prompt_template: "src/resources/prompts/analysis_prompt_template.txt"
  nlg_prompt_template: "src/resources/prompts/nlg_prompt_template.txt"

llm:
  model_type: "llama"
  context_length: 2048
  generation_params:
    temperature: 0.1
    max_new_tokens: 2048

retrieval:
  dense_model_name: "pritamdeka/S-PubMedBert-MS-MARCO"
  similarity_top_k: 3
  rrf_k: 60

analysis:
  confidence_threshold: 0.7
  deterministic_focus: |
    - Treatment frequency documented
    - Goals reviewed or adjusted
    - Medical necessity justified

# --- 7 Habits Personal Development Framework ---
habits_framework:
  enabled: true  # Master toggle for entire habits feature
  
  # Visibility Level: Controls how prominent the habits feature is
  # Options: "subtle" (A), "moderate" (B), "prominent" (C)
  visibility_level: "moderate"  # Default to moderate visibility
  
  # Report Integration Settings
  report_integration:
    show_habit_tags: true  # Show habit tags on individual findings
    show_personal_development_section: true  # Show collapsible section at end of report
    show_habit_tooltips: true  # Show hover tooltips with quick tips
    habit_section_expanded_by_default: false  # Start collapsed (moderate)
    # When visibility_level="prominent", this becomes true
  
  # Dashboard Integration Settings
  dashboard_integration:
    show_growth_journey_tab: true  # Show dedicated habits tab in dashboard
    show_weekly_focus_widget: true  # Show "This Week's Focus" widget
    show_habit_progression_charts: true  # Show habit mastery visualizations
    show_peer_comparison: false  # Anonymous peer comparison (privacy-sensitive)
  
  # AI-Powered Features
  ai_features:
    use_ai_mapping: false  # Use AI for contextual habit mapping (requires LLM)
    use_ai_coaching: false  # Enable AI habit coach assistant
    personalized_strategies: true  # Generate personalized improvement strategies
  
  # Gamification & Motivation
  gamification:
    enabled: true  # Enable achievement system
    show_badges: true  # Show achievement badges
    show_streaks: true  # Show improvement streaks
    show_milestones: true  # Celebrate milestones
    notifications_enabled: false  # Send achievement notifications (off by default)
  
  # Educational Content
  education:
    show_habit_resources: true  # Show detailed habit explanations
    show_clinical_examples: true  # Show clinical application examples
    show_improvement_strategies: true  # Show actionable strategies
    show_templates: true  # Offer habit-based documentation templates
  
  # Privacy & Data
  privacy:
    track_progression: true  # Track habit improvement over time
    anonymous_analytics: true  # Contribute to anonymous benchmarking
    share_achievements: false  # Allow sharing achievements (off by default)
  
  # Advanced Settings
  advanced:
    habit_confidence_threshold: 0.6  # Minimum confidence for habit mapping
    focus_area_threshold: 0.20  # Percentage threshold for "needs focus" (20%)
    mastery_threshold: 0.05  # Percentage threshold for "mastered" (5%)
    weekly_focus_enabled: true  # Generate weekly habit focus
    auto_suggest_templates: true  # Suggest templates based on findings
