name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install -r requirements-dev.txt || true
      - name: Lint (flake8)
        run: |
          pip install flake8 || true
          flake8 || true
      - name: Run tests
        env:
          SECRET_KEY: test-secret
          USE_AI_MOCKS: '1'
        run: |
          pytest -q
      - name: Generate OpenAPI schema
        env:
          SECRET_KEY: test-secret
          USE_AI_MOCKS: '1'
        run: |
          python tools/dump_openapi.py
      - name: Smoke test API import and health endpoints
        env:
          SECRET_KEY: test-secret
          USE_AI_MOCKS: '1'
          DISABLE_EXTERNAL_CHECKS: '1'
        run: |
          python tools/smoke_test.py
      - name: Upload OpenAPI schema artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-schema
          path: |
            openapi.json
            openapi_summary.txt
