name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libxkbcommon-x11-0 libgl1

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run core test suite with coverage
        run: >-
          pytest -m "not heavy and not stability"
          tests/unit tests/logic tests/regression tests/integration tests/api
          --cov=src --cov-report=term --cov-fail-under=55

      - name: Run GUI tests with coverage append
        run: >-
          pytest -m "not heavy" tests/gui
          --cov=src --cov-append --cov-report=term

      - name: Generate coverage reports
        run: |
          coverage xml
          coverage report --fail-under=55

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
