data_sources: []
description: Detailed compliance analysis with regulatory findings
filters: {}
metadata: {}
output_formats:
- html
recipients: []
report_type: compliance_analysis
template_id: compliance_analysis
title: Compliance Analysis Report
