data_sources: []
description: High-level performance and compliance summary
filters: {}
metadata: {}
output_formats:
- html
recipients: []
report_type: executive_summary
template_id: executive_summary
time_range:
  end_time: '2025-10-07T02:04:57.781097'
  start_time: '2025-09-30T02:04:57.781097'
title: Executive Summary
